module.exports = {
	// Base Item --------------------------------------
	belt            : {
		name   : "Giant's Belt",
		perk   : '+200 Base Health',
		id     : 'giantsbelt',
		combos : {
			glove   : 'trapclaw',
			sword   : 'zekesherald',
			rod     : 'morellonomicon',
			bow     : 'titanichydra',
			tear    : 'redemption',
			vest    : 'redbuff',
			cloak   : 'zephyr',
			belt    : 'warmogsarmor',
			spatula : 'frozenmallet',
		},
	},
	bow             : {
		id     : 'recurvebow',
		name   : 'Recurve Bow',
		perk   : '+20% Attack Speed',
		combos : {
			glove   : 'repeatingcrossbow',
			sword   : 'giantslayer',
			rod     : 'guinsoosrageblade',
			bow     : 'rapidfirecannon',
			tear    : 'statikkshiv',
			vest    : 'phantomdancer',
			cloak   : 'runaanshurricane',
			spatula : 'bladeoftheruinedking',
			// belt    : 'titanichydra',
		},
	},
	cloak           : {
		id     : 'negatroncloak',
		name   : 'Negatron Cloak',
		perk   : '+20 Magic Resist',
		combos : {
			glove   : 'quicksilver',
			sword   : 'bloodthirster',
			rod     : 'ionicspark',
			tear    : 'hush',
			vest    : 'swordbreaker',
			cloak   : 'dragonsclaw',
			spatula : 'talismanoflight',
			// bow     : 'runaanshurricane',
			// belt    : 'zephyr',
		},
	},
	glove           : {
		id     : 'sparringgloves',
		name   : 'Sparring Gloves',
		perk   : '+10& Dodge Chance, +10% Crit Chance',
		combos : {
			glove   : 'thiefsgloves',
			sword   : 'infinityedge',
			rod     : 'jeweledgauntlet',
			tear    : 'handofjustice',
			vest    : 'iceborngauntlet',
			spatula : 'berserkeraxe',
			// bow     : 'repeatingcrossbow',
			// cloak   : 'quicksilver',
			// belt    : 'trapclaw',
		},
	},
	rod             : {
		id     : 'needlesslylargerod',
		name   : 'Needlessly Large Rod',
		perk   : '+20% Spell Power',
		combos : {
			sword   : 'hextechgunblade',
			rod     : 'rabadonsdeathcap',
			tear    : 'ludensecho',
			vest    : 'locketoftheironsolari',
			spatula : 'infernocinder',
			// glove   : '',
			// bow     : '',
			// cloak   : '',
			// belt    : '',
		},
	},
	spatula         : {
		id     : 'spatula',
		name   : 'Spatula',
		perk   : 'Something',
		combos : {
			sword   : 'youmuusghostblade',
			tear    : 'magescap',
			vest    : 'wardensmail',
			spatula : 'forceofnature',
			// glove   : '',
			// rod     : '',
			// bow     : '',
			// cloak   : '',
			// belt    : '',
		},
	},
	sword           : {
		name   : 'B.F. Sword',
		perk   : '+20 Attack Damage',
		id     : 'bfsword',
		combos : {
			sword : 'deathblade',
			tear  : 'spearofshojin',
			vest  : 'guardianangel',
			// glove   : 'infinityedge',
			// rod     : 'hextechgunblade',
			// bow     : 'giantslayer',
			// cloak   : 'bloodthirster',
			// belt    : 'zekesherald',
			// spatula : 'youmuusghostblade',
		},
	},
	tear            : {
		id     : 'tearofthegoddess',
		name   : 'Tear of the Goddess',
		perk   : '+20% Starting Mana',
		combos : {
			tear : 'seraphsembrace',
			vest : 'frozenheart',
			// glove   : '',
			// sword   : '',
			// rod     : '',
			// bow     : '',
			// cloak   : '',
			// belt    : '',
			// spatula : '',
		},
	},
	vest            : {
		name   : 'Chain Vest',
		perk   : '+20 Armor',
		id     : 'chainvest',
		combos : {
			vest : 'thornmail',
			// sword   : 'guardianangel',
			// glove   : 'iceborngauntlet',
			// rod     : 'locketoftheironsolari',
			// bow     : 'phantomdancer',
			// tear    : 'frozenheart',
			// cloak   : 'swordbreaker',
			// belt    : 'redbuff',
			// spatula : 'wardensmail',
		},
	},

	// Combos -----------------------------------------
	belt_belt       : {
		id        : 'warmogsarmor',
		perk      : 'Regenerate 6% missing HP per sec',
		perk_full : 'Wearer regenerates 6% of missing HP per second',
	},
	belt_bow        : {
		id        : 'titanichydra',
		perk      : 'attack deals 3% max HP to target and adjacent enemies behind',
		perk_full : 'attack deals 3% max HP to target and adjacent enemies behind them',
	},
	belt_cloak      : {
		id        : 'zephyr',
		perk      : 'Banish an enemy for 6s on combat start',
		perk_full : 'On start of combat, banish an enemy for 6 seconds',
	},
	belt_glove      : {
		id        : 'trapclaw',
		perk      : 'Start w/ spell shield, enemy breaker stunned for 4s',
		perk_full : 'Wearer starts combat with spell shield, stuns enemy who breaks it for 4 seconds',
	},
	belt_rod        : {
		id        : 'morellonomicon',
		perk      : "Spells deal burn dmg of 20% of enemy's max HP over 10s, prevents healing",
		perk_full : "Spells deal burn damage equal to 20% of enemy's max HP over 10 seconds and prevents healing",
	},
	belt_spatula    : {
		id        : 'frozenmallet',
		perk      : 'Also Glacial',
		perk_full : 'Wearer is also glacial',
	},
	belt_sword      : {
		id        : 'zekesherald',
		perk      : 'At start, +20% Attack Speed for allies 2 spaces to L&R',
		perk_full : 'At start, allies 2 spaces to left and right gain +20% attack speed',
	},
	belt_tear       : {
		id        : 'redemption',
		perk      : 'At 30% health, heal nearby allies for 1200 HP',
		perk_full : 'At 30% health, heal all nearby allies for 1200 HP',
	},
	belt_vest       : {
		id        : 'redbuff',
		perk      : 'Attacks burn for 20% max HP over 10s & disable healing',
		perk_full : 'Attacks burn for 20% of max HP over 10 seconds and disable healing',
	},
	bow_bow         : {
		id        : 'rapidfirecannon',
		perk      : 'Doubles attack range',
		perk_full : 'Attack range is doubled',
	},
	bow_cloak       : {
		id        : 'runaanshurricane',
		perk      : 'Attacks extra enemy & deals 60% dmg (on hit effects)',
		perk_full : 'Attacks one additional enemy and deals 60% damage (applies on hit effects)',
	},
	bow_glove       : {
		id        : 'repeatingcrossbow',
		perk      : 'On death, pass item to ally. +30% crit chance & attack speed (stacks)',
		perk_full : 'On death, item passes to an ally. gain additional 30% crit chance and attack speed (stacks)',
	},
	bow_rod         : {
		id        : 'guinsoosrageblade',
		perk      : '+5% attack speed on attacks (stacks infinitely)',
		perk_full : 'Attacks give 5% attack speed. stacks infinitely',
	},
	bow_spatula     : {
		id        : 'bladeoftheruinedking',
		perk      : 'Also Blademaster',
		perk_full : 'Wearer is also a blademaster',
	},
	bow_sword       : {
		id        : 'giantslayer',
		perk      : "Attacks deal +9% enemy's current HP as physical dmg",
		perk_full : "Attacks deal additional 9% of enemy's current HP as physical damage",
	},
	bow_tear        : {
		id        : 'statikkshiv',
		perk      : 'Every 3rd attack, deal 100 dmg to 2 extra targets',
		perk_full : 'Every 3rd attack deals 100 damage to 2 additional targets',
	},
	bow_vest        : {
		id        : 'phantomdancer',
		perk      : 'Dodge all crit strikes',
		perk_full : 'Wearer dodges all critical strikes',
	},
	cloak_cloak     : {
		id        : 'dragonsclaw',
		perk      : '50% magic dmg resistance',
		perk_full : '50% resistance to magic damage',
	},
	cloak_glove     : {
		id        : 'quicksilver',
		perk      : 'Prevents next CC effect (refreshes every 3s)',
		perk_full : 'Prevents next cc effect to wearer. refreshes every 3 seconds',
	},
	cloak_rod       : {
		id        : 'ionicspark',
		// perk:'On enemy spell cast, they take 90 true dmg',
		perk       : 'Enemy takes 90 true dmg on spell cast',
		perk_full : 'Whenever an enemy casts a spell, they take 90 true damage',
	},
	cloak_spatula   : {
		id        : 'talismanoflight',
		perk      : 'Also Light',
		perk_full : 'Wearer is also light',
	},
	cloak_sword     : {
		id        : 'bloodthirster',
		perk      : 'Attacks heal for 40% of dmg',
		perk_full : 'Attacks heal for 40% of damage',
	},
	cloak_tear      : {
		id        : 'hush',
		perk      : 'Attacks have 25% chance to mana lock for 4s',
		perk_full : 'Attacks have 25% chance to mana lock for 4 seconds',
	},
	cloak_vest      : {
		id        : 'swordbreaker',
		perk      : 'Attacks have 25% chance to disarm for 3s',
		perk_full : 'Attacks have 25% chance to disarm for 3 seconds',
	},
	glove_glove     : {
		id        : 'thiefsgloves',
		perk      : 'At start, gain 2 temp items (takes all slots)',
		perk_full : 'Takes all item slots. on round start, gain 2 temporary items',
	},
	glove_rod       : {
		id        : 'jeweledgauntlet',
		perk      : 'Abilities can crit strike',
		perk_full : 'Your abilities can critically strike',
	},
	glove_spatula   : {
		id        : 'berserkeraxe',
		perk      : 'Also Berserker',
		perk_full : 'Wearer is also berserker',
	},
	glove_sword     : {
		id        : 'infinityedge',
		perk      : 'Crit strikes deal +125% dmg',
		perk_full : 'Critical strikes deal +125% damage',
	},
	glove_tear      : {
		id        : 'handofjustice',
		perk      : 'On start, +50% dmg or +50 life on hit until round end',
		perk_full : 'On round start, gain +50% damage or +50 life on hit until end of round',
	},
	glove_vest      : {
		id        : 'iceborngauntlet',
		perk      : 'Dodges create expandable 25% attack speed slow zone',
		perk_full : 'On dodge, create an expandable 25% attack speed slow zone',
	},
	rod_rod         : {
		id        : 'rabadonsdeathcap',
		perk      : '+75% ability dmg',
		perk_full : "Wearer's ability damage increased by 75%",
	},
	rod_spatula     : {
		id        : 'infernocinder',
		perk      : 'Also Inferno',
		perk_full : 'Wearer is also Inferno',
	},
	rod_sword       : {
		id        : 'hextechgunblade',
		perk      : 'Heal for 25% of dmg dealt',
		perk_full : 'Heal for 25% of all damage dealt',
	},
	rod_tear        : {
		id        : 'ludensecho',
		perk      : '150 splash dmg on ability hit',
		perk_full : 'Deal 150 splash damage on ability hit',
	},
	rod_vest        : {
		id        : 'locketoftheironsolari',
		perk      : 'At start, 300 shield for 8s to wearer and allies 2 spaces L&R',
		perk_full : 'At start of combat, wearer and allies 2 spaces to left and right get 300 shield for 8 seconds',
	},
	spatula_spatula : {
		id        : 'forceofnature',
		perk      : '+1 team size',
		perk_full : 'Gain + team size',
	},
	spatula_sword   : {
		id        : 'youmuusghostblade',
		perk      : 'Also Assassin',
		perk_full : 'Wearer is also assassin',
	},
	spatula_tear    : {
		id        : 'magescap',
		perk      : 'Also Mage',
		perk_full : 'Wearer is also a mage',
	},
	spatula_vest    : {
		id        : 'wardensmail',
		perk      : 'Also Warden',
		perk_full : 'Wearer is also a warden',
	},
	sword_sword     : {
		id        : 'deathblade',
		perk      : 'On kill/assist, +15 attack (stacks infinitely)',
		perk_full : 'On kill or assist, gain +15 attack, stacks infinitely',
	},
	sword_tear      : {
		id        : 'spearofshojin',
		perk      : 'After cast, +18% max mana per attack',
		perk_full : 'After casting, gain 18% of max mana per attack',
	},
	sword_vest      : {
		id        : 'guardianangel',
		perk      : 'Revives with 400HP after 2s',
		perk_full : 'Revives champ with 400 HP after 2 seconds',
	},
	tear_tear       : {
		id        : 'seraphsembrace',
		perk      : '+20 mana each time a spell is cast',
		perk_full : 'Regain 20 mana each time a spell is cast',
	},
	tear_vest       : {
		id        : 'frozenheart',
		perk      : '-25% attack speed for 1s to adjacent enemies',
		perk_full : 'Adjacent enemies lose 25% attack speed for 1 second',
	},
	vest_vest       : {
		id        : 'thornmail',
		perk      : 'Reflect 100% mitigated dmg taken from attacks as magic dmg',
		perk_full : 'Reflect 100% of mitigated damage taken from attacks as magic damage',
	},
};
