module.exports = {
  "B.F. Sword": "+15 Attack Damage.",
  "Chain Vest": "+20 Armor.",
  "Giant's Belt": "+200 Health.",
  "Needlessly Large Rod": "+20% Spell Damage.",
  "Negatron Cloak": "+25 Magic Resist.",
  "Recurve Bow": "+15% Attack Speed",
  "Spatula": "It must do something...",
  "Sparring Gloves": "+10% Critical Strike Chance. +10% Dodge Chance",
  "Tear of the Goddess": "+20 Mana.",
  "Berserker Axe": "Wearer is also a Berserker.",
  "Blade of the Ruined King": "Wearer is also a Blademaster.",
  "Bloodthirster": "Basic Attacks heal the wearer for 50% of the damage dealt.",
  "Bramble Vest": "Negates bonus damage from incoming critical hits. On being hit by a Basic Attack, deal 100/140/200 ★ magic damage to all nearby enemies (once every 1second max).",
  "Cursed Blade": "Basic Attacks have a 20% chance on-hit to decrease the target' star level by 1 for the rest of combat.",
  "Darkin": "Wearer is also a Demon.",
  "Deathblade": "Whenever the wearer kills or participates in killing an enemy, gain +15 Attack Damage for the remainder of combat. This effect can stack any number of times.",
  "Dragon's Claw": "Wearer gains 50% resistance to magic damage.",
  "Force of Nature": "Wearer's team gains +1 maximum team size.",
  "Frozen Heart": "Reduces the Attack Speed of nearby enemies by 40% (stacking increases the radius of this effect).",
  "Frozen Mallet": "Wearer is also a Glacial.",
  "Giant Slayer": "The wearer's basic attacks deal an additional 9% of the target's current health as physical damage.",
  "Guardian Angel": "When the wearer dies, they cleanse negative effects and revive with up to 500 Health after a 2 second delay. This effect can trigger once per combat.",
  "Guinsoo's Rageblade": "Basic Attacks grant the wearer +5% bonus Attack Speed for the rest of combat. This effect can stack any number of times.",
  "Hand of Justice": "At the beginning of each planning phase, the wearer gains one of the following: Basic Attacks and Spells deal +50% Damage or Basic Attacks heal 50 Health on-hit.",
  "Hextech Gunblade": "Basic Attacks and spells heal the wearer for 33% of the damage dealt.",
  "Hush": "Basic Attacks have a 20% chance to silence the target on-hit, prevent the enemy from gaining mana for 4 seconds.",
  "Iceborne Gauntlet": "After casting a spell, the wearer’s next Basic Attack freezes the target for 2.5 seconds.",
  "Inferno Cinder": "Wearer is also an Inferno.",
  "Infinity Edge": "The wearer gains +125% Critical Strike Damage.",
  "Ionic Spark": "Enemies within 3 hexes that cast a spell are zapped, taking magic damage equal to 200% of their max Mana.",
  "Jeweled Gauntlet": "The wearer's spells can critically strike.",
  "Knight's Vow": "Wearer is also a Knight.",
  "Last Whisper": "[UNIQUE] Critical hits reduce the target's Armor by 90% for 3 seconds. This effect does not stack.",
  "Locket of the Iron Solari": "When combat begins, the wearer and all allies within 2 hexes in the same row gain a shield that blocks 250/275/350 ★ damage for 8 seconds.",
  "Luden's Echo": "When the wearer deals damage with their spell, the first target hit and up to 3 nearby enemies are dealt an additional 125/175/250 ★ magic damage.",
  "Mage's Cap": "Wearer is also a Mage.",
  "Mittens": "Wearer is also a yordle.",
  "Morellonomicon": "When the wearer deals damage with their spell, they burn the target, dealing 18% of the target's Maximum Health as true damage over 10 seconds and reducing healing by 80% for the duration of the burn. A champion can only have one burn effect at a time, preferring the strongest.",
  "Phantom Dancer": "Wearer dodges all Critical Strikes.",
  "Quicksilver": "[UNIQUE] The wearer is immune to Crowd Control.",
  "Rabadon's Deathcap": "Wearer gains +50% Spell Power Amplification. (All sources of Spell Power are 50% more effective)",
  "Rapid Firecannon": "Wearer gains +100% Attack Range.",
  "Red Buff": "Wearer's Basic Attacks burn the target on-hit, dealing 18% of the target's Maximum Health as true damage over 10 seconds and reducing healing by 80% for the duration of the burn. A champion can only have one burn effect at a time, preferring the strongest.",
  "Redemption": "When the wearer falls below 30% Health, nearby allies are healed for 1200 Health after a 2.5 second delay. This effect can trigger once per combat.",
  "Repeating Crossbow": "When the wearer dies, Repeating Crossbow is re-equipped to a new ally. Each time Repeating Crossbow is re-equipped, it grants additional +30% Attack Speed and +30% Critical Strike Chance for the remainder of combat. This effect can stack any number of times.",
  "Runaan's Hurricane": "Basic Attacks fire an additional missile at another nearby enemy, dealing 60% of the wearer's Attack damage and applying on-hit effects.",
  "Seraph's Embrace": "After casting their spell, the wearer restores 20 Mana.",
  "Spear of Shojin": "After casting their spell, the wearer's Basic Attacks restore 18% of their Maximum Mana.",
  "Statikk Shiv": "Every third Basic Attack from the wearer deals 80 magical damage to 3/4/5 ★ enemies.",
  "Sword Breaker": "Wearer's Basic Attacks have a 25% chance to disarm the target for 3 seconds, preventing that enemy from Basic Attacking.",
  "Talisman of Light": "Wearer is also a Light.",
  "Thief's Gloves": "At the beginning of each planning phase, the wearer equips 2 temporary items. Temporary items increase in power based on your player level.",
  "Thornmail": "When the wearer is hit by a Basic Attack, they reflect 100% of the mitigated damage as magic damage.",
  "Titanic Hydra": "Basic Attacks deal an additional 3% of the wearer's Maximum Health as magic damage to the target and adjacent enemies behind them.",
  "Titan's Resolve": "When the wearer is hit or inflicts a critical hit, they gain a 2% stacking damage bonus, up to 100%. At 50 stacks, the wearer gains 25 Armor and Magic Resistance, and increases in size. Resets every round.",
  "Trap Claw": "At the beginning of combat, the wearer gains a shield that blocks the first enemy spell that hits them. The enemy that breaks the shield is stunned for 4 seconds.",
  "Warden's Mail": "Wearer is also a Warden.",
  "Warmog's Armor": "Wearer regenerates 6% of their missing Health per second.",
  "Youmuu's Ghostblade": "Wearer is also an Assassin.",
  "Yuumi": "Wearer is also a Sorcerer.",
  "Zeke's Herald": "When combat begins, the wearer and all allies within 2 hexes in the same row gain +15% Attack Speed for the rest of combat.",
  "Zephyr": "When combat begins, the wearer summons a whirlwind on the opposite side of the arena that removes the closest enemy from combat for 6 seconds."
}